; Auto-generated. Do not edit!


(cl:in-package communication-msg)


;//! \htmlinclude moveGoal.msg.html

(cl:defclass <moveGoal> (roslisp-msg-protocol:ros-message)
  ((robot_id
    :reader robot_id
    :initarg :robot_id
    :type cl:integer
    :initform 0))
)

(cl:defclass moveGoal (<moveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication-msg:<moveGoal> is deprecated: use communication-msg:moveGoal instead.")))

(cl:ensure-generic-function 'robot_id-val :lambda-list '(m))
(cl:defmethod robot_id-val ((m <moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication-msg:robot_id-val is deprecated.  Use communication-msg:robot_id instead.")
  (robot_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveGoal>) ostream)
  "Serializes a message object of type '<moveGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'robot_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveGoal>) istream)
  "Deserializes a message object of type '<moveGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveGoal>)))
  "Returns string type for a message object of type '<moveGoal>"
  "communication/moveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveGoal)))
  "Returns string type for a message object of type 'moveGoal"
  "communication/moveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveGoal>)))
  "Returns md5sum for a message object of type '<moveGoal>"
  "643c2c9b3dd26758833f013bbe8b0a36")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveGoal)))
  "Returns md5sum for a message object of type 'moveGoal"
  "643c2c9b3dd26758833f013bbe8b0a36")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveGoal>)))
  "Returns full string definition for message of type '<moveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 robot_id  # Specify which robot we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveGoal)))
  "Returns full string definition for message of type 'moveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 robot_id  # Specify which robot we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'moveGoal
    (cl:cons ':robot_id (robot_id msg))
))
