; Auto-generated. Do not edit!


(cl:in-package communication-msg)


;//! \htmlinclude move_actionFeedback.msg.html

(cl:defclass <move_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass move_actionFeedback (<move_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <move_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'move_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication-msg:<move_actionFeedback> is deprecated: use communication-msg:move_actionFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <move_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication-msg:percent_complete-val is deprecated.  Use communication-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <move_actionFeedback>) ostream)
  "Serializes a message object of type '<move_actionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <move_actionFeedback>) istream)
  "Deserializes a message object of type '<move_actionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<move_actionFeedback>)))
  "Returns string type for a message object of type '<move_actionFeedback>"
  "communication/move_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'move_actionFeedback)))
  "Returns string type for a message object of type 'move_actionFeedback"
  "communication/move_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<move_actionFeedback>)))
  "Returns md5sum for a message object of type '<move_actionFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'move_actionFeedback)))
  "Returns md5sum for a message object of type 'move_actionFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<move_actionFeedback>)))
  "Returns full string definition for message of type '<move_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'move_actionFeedback)))
  "Returns full string definition for message of type 'move_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <move_actionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <move_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'move_actionFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
