; Auto-generated. Do not edit!


(cl:in-package communication-msg)


;//! \htmlinclude moveResult.msg.html

(cl:defclass <moveResult> (roslisp-msg-protocol:ros-message)
  ((total_time_used
    :reader total_time_used
    :initarg :total_time_used
    :type cl:integer
    :initform 0))
)

(cl:defclass moveResult (<moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name communication-msg:<moveResult> is deprecated: use communication-msg:moveResult instead.")))

(cl:ensure-generic-function 'total_time_used-val :lambda-list '(m))
(cl:defmethod total_time_used-val ((m <moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader communication-msg:total_time_used-val is deprecated.  Use communication-msg:total_time_used instead.")
  (total_time_used m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveResult>) ostream)
  "Serializes a message object of type '<moveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_time_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_time_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_time_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_time_used)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveResult>) istream)
  "Deserializes a message object of type '<moveResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_time_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_time_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_time_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_time_used)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveResult>)))
  "Returns string type for a message object of type '<moveResult>"
  "communication/moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveResult)))
  "Returns string type for a message object of type 'moveResult"
  "communication/moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveResult>)))
  "Returns md5sum for a message object of type '<moveResult>"
  "7d783291dfe0333a693a075000a0e15a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveResult)))
  "Returns md5sum for a message object of type 'moveResult"
  "7d783291dfe0333a693a075000a0e15a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveResult>)))
  "Returns full string definition for message of type '<moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_time_used~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveResult)))
  "Returns full string definition for message of type 'moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_time_used~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveResult
    (cl:cons ':total_time_used (total_time_used msg))
))
