// Generated by gencpp from file communication/move_actionResult.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_MOVE_ACTIONRESULT_H
#define COMMUNICATION_MESSAGE_MOVE_ACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication
{
template <class ContainerAllocator>
struct move_actionResult_
{
  typedef move_actionResult_<ContainerAllocator> Type;

  move_actionResult_()
    : total_time_used(0)  {
    }
  move_actionResult_(const ContainerAllocator& _alloc)
    : total_time_used(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_time_used_type;
  _total_time_used_type total_time_used;





  typedef boost::shared_ptr< ::communication::move_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication::move_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct move_actionResult_

typedef ::communication::move_actionResult_<std::allocator<void> > move_actionResult;

typedef boost::shared_ptr< ::communication::move_actionResult > move_actionResultPtr;
typedef boost::shared_ptr< ::communication::move_actionResult const> move_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication::move_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication::move_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication::move_actionResult_<ContainerAllocator1> & lhs, const ::communication::move_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_time_used == rhs.total_time_used;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication::move_actionResult_<ContainerAllocator1> & lhs, const ::communication::move_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::communication::move_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::move_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::move_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::move_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::move_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::move_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication::move_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d783291dfe0333a693a075000a0e15a";
  }

  static const char* value(const ::communication::move_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d783291dfe0333aULL;
  static const uint64_t static_value2 = 0x693a075000a0e15aULL;
};

template<class ContainerAllocator>
struct DataType< ::communication::move_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication/move_actionResult";
  }

  static const char* value(const ::communication::move_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication::move_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 total_time_used\n"
;
  }

  static const char* value(const ::communication::move_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication::move_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_time_used);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication::move_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication::move_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "total_time_used: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_time_used);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MESSAGE_MOVE_ACTIONRESULT_H
