// Generated by gencpp from file communication/move_actionGoal.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_MOVE_ACTIONGOAL_H
#define COMMUNICATION_MESSAGE_MOVE_ACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication
{
template <class ContainerAllocator>
struct move_actionGoal_
{
  typedef move_actionGoal_<ContainerAllocator> Type;

  move_actionGoal_()
    : robot_id(0)  {
    }
  move_actionGoal_(const ContainerAllocator& _alloc)
    : robot_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::communication::move_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication::move_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct move_actionGoal_

typedef ::communication::move_actionGoal_<std::allocator<void> > move_actionGoal;

typedef boost::shared_ptr< ::communication::move_actionGoal > move_actionGoalPtr;
typedef boost::shared_ptr< ::communication::move_actionGoal const> move_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication::move_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication::move_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication::move_actionGoal_<ContainerAllocator1> & lhs, const ::communication::move_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication::move_actionGoal_<ContainerAllocator1> & lhs, const ::communication::move_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::communication::move_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::move_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::move_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::move_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::move_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::move_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication::move_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "643c2c9b3dd26758833f013bbe8b0a36";
  }

  static const char* value(const ::communication::move_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x643c2c9b3dd26758ULL;
  static const uint64_t static_value2 = 0x833f013bbe8b0a36ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication::move_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication/move_actionGoal";
  }

  static const char* value(const ::communication::move_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication::move_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 robot_id  # Specify which robot we want to use\n"
;
  }

  static const char* value(const ::communication::move_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication::move_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication::move_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication::move_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MESSAGE_MOVE_ACTIONGOAL_H
